<?php
//use App\Models\User;
require "src\Classes\Models\User.php";

class UserTest extends \PHPUnit\Framework\TestCase
{
    private $user;

    protected function setUp(): void
    {
        $this->user = new App\Models\User;
        $this->user->setAge(33);
    }

    protected function tearDown(): void
    {
        //parent::tearDown(); // TODO: Change the autogenerated stub
    }

//    /**
//     * @dataProvider userProvider
//     */
//    // Будет тбрать згначения для $age из масива возращаемого функцией userProvider()
//    public function testAge($age)
//    {
//        $this->assertEquals($age,$this->user->getAge());
//    }
//    public function userProvider(){
//        return [
//            'one'=>[2],
//            [3],
//            [33]
//        ];
//    }
//
//

    public function testAge2()
    {


        $this->assertEquals(33,$this->user->getAge());
        $this->assertEquals(22,$this->user->getAge());
        return 3;
    }

//    /**
//     * @depends testAge2
//     */
//    // в аргумент $age попадет возвращаемое значение из метода testAge2()
//    public function testAge3($age)
//    {
//        throw new Exception('some ,asage');
//        $this->assertEquals($age,$this->user->getAge());
//    }


}